---
title: "Analizando los Datos de djbpublico.contraloria.gov.py"
output: html_notebook
---

Para correr el primer bloque es necesario instalar pacman. En RStudio puedes hacerlo en: Tools - Install Packages

```{r}
pacman::p_load(pdftools, tidyverse, tesseract)
```

Obtenemos todos los nombres de los PDFs

```{r}
pdf_files <- Sys.glob("contraloria_pdfs/*.pdf")
head(pdf_files)
```
Separamos los PDFs en digital/scanned 

```{r}
scanned_folder <- "scanned_pdfs"
digital_folder <- "digital_pdfs"


for (pdf in pdf_files)
{
  
  tryCatch(
    expr = {
      if(pdf_text(pdf)[1] == ""){
        print(paste("is scanned -- ", pdf))
        
        # Copy file to scanned directory
        file.copy(pdf, scanned_folder)
        
      } else if (pdf_text(pdf)[1] != "") {
        print(paste("is digital -- ", pdf))
        
        # Copy file to digital directory
        file.copy(pdf, digital_folder)
        
      }
    },
    error = function(e){
      print(e)
    })
}
```

Prueba de OCR

Si no tienes instalado el modelo en español de tesseract, quita el comentario de y corré al siguiente bloque

```{r}
# tesseract_download('spa', datapath = NULL, progress = interactive())
```

```{r}
es <- tesseract::tesseract("spa")
text <- tesseract::ocr("contraloria_pdfs/3068-434900-miguel-carrizosagaliano-2009-1.pdf", engine = es)
cat(text)
```

```{r}
text2 <- pdf_ocr_text("contraloria_pdfs/3068-434900-miguel-carrizosagaliano-2009-1.pdf", language = "spa")
cat(text2)
```


